### PR TITLE
Update: Added Validation Form for add product page

### PR DESCRIPTION
**Pull request by chaitanya005**
- Resolved issues while adding Category
- Added Form Validations using Formik Validation Schema for add Product Page

### CODE REVIEW

**Comment by iMagesh** [comment]
@chaitanya005 you have to pull the updates and fix these since Abhishek has made a lot of changes to products and variants. You might have to rewrite these things.

**Comment by chaitanya005** [comment]
okay @iMagesh

**Comment by chaitanya005** [comment]
@iMagesh I have added Validations for Add Product and Add Variant Pages using Formik Forms. please check them

**Comment by iMagesh** [comment]
can you resolve the conflict @chaitanya005

**Comment by chaitanya005** [comment]
resolved @iMagesh. please check

**Pull request merged**
